console_title_template = '{{ .Shell }} in {{ .Folder }}'
version = 3
final_space = true

[palette]
  black = '#262B44'
  dimmed = '#6c6c6c'
  blue = '#4B95E9'
  green = '#59C9A5'
  orange = '#F07623'
  red = '#D81E5B'
  white = '#E0DEF4'
  yellow = '#F3AE35'

[upgrade]
  source = 'cdn'
  interval = '168h'
  auto = false
  notice = false

[[blocks]]
  type = 'prompt'
  alignment = 'left'
  newline = true

  [[blocks.segments]]
    foreground = 'p:green'
    background = 'transparent'
    type = 'path'
    style = 'plain'
    template = "{{ path .Path .Location }} " 

    [blocks.segments.properties]
      style = 'agnoster_short'
      folder_icon = ' 󰝰 '

  [[blocks.segments]]
    type = 'git'
    style = 'plain'
    foreground = 'p:dimmed'
    template = ' {{ .HEAD }}{{ if or (.Working.Changed) (.Staging.Changed) }}*{{ end }} <cyan>{{ if gt .Behind 0 }}⇣{{ end }}{{ if gt .Ahead 0 }}⇡{{ end }}</>' 
    
    [[blocks.segments.path]]
      branch_icon = ''
      commit_icon = '@'
      fetch_status = true

 [[blocks]]
  type = 'prompt'
  alignment = 'left'
  newline = true

  [[blocks.segments]]
    type = 'text'
    foreground = 'p:green'
    background = 'transparent'
    style = 'plain'
    template = '❱'  # U+2761 (chunkier arrow)

    [blocks.segments.properties]
      style = 'full'
  
  [transient_prompt]
    background = "transparent"
    foreground = "#ffffff"
    template = "{{ .Shell }} ❱ "
    newline = true

 



